if(EXISTS "D:/repos/csad2526ki402varvarychroman3/unit_tests[1]_tests.cmake")
  include("D:/repos/csad2526ki402varvarychroman3/unit_tests[1]_tests.cmake")
else()
  add_test(unit_tests_NOT_BUILT unit_tests_NOT_BUILT)
endif()
